-- If you want to create the table yourself, for example to experiment with
-- table structure, you need to drop the table created by JPA first. 
-- Note that the DDL statements (DROP/CREATE TABLE) must be one-liner.
DROP TABLE PERSON CASCADE;
CREATE TABLE PERSON ( ID INTEGER PRIMARY KEY, FIRSTNAME VARCHAR(32), LASTNAME VARCHAR(32), DATEOFBIRTH DATE);

-- Person
INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES (1, 'Albert', 'Einstein', '1879-03-14');

-- Journal
INSERT INTO JOURNAL (ID, CATEGORY, MESSAGE) VALUES (1, 'HUMAN', 'Message with one parameter %1');
INSERT INTO JOURNAL (ID, CATEGORY, MESSAGE) VALUES (2, 'MACHINE', 'Message with two parameters %1 and %2');

INSERT INTO JOURNALPARAM (JOURNAL_ID, POSITION, PARAMETER) VALUES (1, 1, 'FIRST');
INSERT INTO JOURNALPARAM (JOURNAL_ID, POSITION, PARAMETER) VALUES (2, 1, 'FIRST');
INSERT INTO JOURNALPARAM (JOURNAL_ID, POSITION, PARAMETER) VALUES (2, 2, 'SECOND');

-- ORDER
INSERT INTO RETAIL_ORDER (ID, CUSTOMER, DATE, STATUS) VALUES (1, 'Customer1', '2020-05-20', 'Completed');
INSERT INTO RETAIL_ORDER (ID, CUSTOMER, DATE, STATUS) VALUES (2, 'Customer2', '2020-05-20', 'Prepare shipping');

INSERT INTO ITEM (ORDER_ID, POSITION, ARTICLE, AMOUNT, PRICE) VALUES (1, 1, 'HP Desktop PC', 1, 600);
INSERT INTO ITEM (ORDER_ID, POSITION, ARTICLE, AMOUNT, PRICE) VALUES (1, 2, 'HP 14 Monitor', 1, 200);
INSERT INTO ITEM (ORDER_ID, POSITION, ARTICLE, AMOUNT, PRICE) VALUES (2, 1, 'Apple MacBook', 1, 1500);

-- Post
INSERT INTO POST (ID, TITLE) VALUES (1, 'First Post');

INSERT INTO COMMENT(POST_ID, ID, REVIEW) VALUES (1, 1, 'First comment');

-- Article
INSERT INTO ARTICLE(ID, TYPE, NAME) VALUES (1, 'DESKTOP', 'Gamer Desktop');
INSERT INTO ARTICLE_DESKTOP(ID, PERIPHERAL) VALUES (1, 'Logitec Mouse+Keyboard');
INSERT INTO ARTICLE(ID, TYPE, NAME) VALUES (2, 'LAPTOP', 'Gamer Laptop');
INSERT INTO ARTICLE_LAPTOP(ID, BATTERY) VALUES (1, 'Lithium 5000A');