-- Person
INSERT INTO Person (ID, FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES (1, 'Albert', 'Einstein', '1879-03-14');

-- Journal
INSERT INTO Journal (ID, CATEGORY, MESSAGE) VALUES (1, 'HUMAN', 'Message with one parameter %1');
INSERT INTO Journal (ID, CATEGORY, MESSAGE) VALUES (2, 'MACHINE', 'Message with two parameters %1 and %2');

INSERT INTO JournalParam (JOURNAL_ID, POSITION, PARAMETER) VALUES (1, 1, 'FIRST');
INSERT INTO JournalParam (JOURNAL_ID, POSITION, PARAMETER) VALUES (2, 1, 'FIRST');
INSERT INTO JournalParam (JOURNAL_ID, POSITION, PARAMETER) VALUES (2, 2, 'SECOND');

-- ORDER
INSERT INTO RETAIL_ORDER (ID, CUSTOMER, DATE, STATUS) VALUES (1, 'Customer1', '2020-05-20', 'Completed');
INSERT INTO RETAIL_ORDER (ID, CUSTOMER, DATE, STATUS) VALUES (2, 'Customer2', '2020-05-20', 'Prepare shipping');

INSERT INTO ITEM (ORDER_ID, POSITION, ARTICLE, AMOUNT, PRICE) VALUES (1, 1, 'HP Desktop PC', 1, 600);
INSERT INTO ITEM (ORDER_ID, POSITION, ARTICLE, AMOUNT, PRICE) VALUES (1, 2, 'HP 14 Monitor', 1, 200);
INSERT INTO ITEM (ORDER_ID, POSITION, ARTICLE, AMOUNT, PRICE) VALUES (2, 1, 'Apple MacBook', 1, 1500);

-- Post
INSERT INTO POST (ID, TITLE) VALUES (1, 'First Post');

INSERT INTO COMMENT(POST_ID, ID, REVIEW) VALUES (1, 1, 'First comment');